### ISSUE TITLE
Score should be reset to 0 after a build fail.

### ISSUE THREAD

**Issue by vinaysetty** [autograde/quickfeed#391]
Students sometimes try some methods to see if their solution is working (for e.g, using a different method than what was asked in the assignment) and get high score. But later on when the build fails then the score is not reset to 0. Student can misuse this and keep past score ask for approval.

**Comment by vinaysetty** [comment]
attaching an example, this case student has 91% score even though build fails. 
![Screenshot 2021-01-22 at 11 49 21](https://user-images.githubusercontent.com/1608263/105481916-f7b41480-5ca7-11eb-86c1-645a07fe4637.png)

**Comment by meling** [comment]
This was a conscious decision to `keep approved status if already approved` (see [code here](https://github.com/autograde/quickfeed/blob/master/ci/run_tests.go#L107)). The rational for this was that students could then continue to work on their code without fear that their existing approvals would be reverted. This has saved us from a fair bit of churn as students messed up their code bases, that would otherwise have caused problems. Obviously, if the assignment is `autoapprove`, then this can be a problem.

I'm certainly willing to reconsider this decision. Please submit a PR and corresponding test cases that we can consider for inclusion.

**Comment by vinaysetty** [comment]
Actually the bug is not about approved status just score. In this example it was approved incidentally. But the score doesn’t reset to 0 even in cases when it is not approved.

**Comment by meling** [comment]
Okay, I see. Reseting the score must be done by the Python scoring framework. You would probably need to have some mechanism to catch the failure and replace the score output, since this is all just strings in the output stream. 

Note that QuickFeed can handle two Score objects for the same test in the output stream, e.g:
```
{"Secret":"","TestName":"TestFibonacci","Score":0,"MaxScore":28,"Weight":20}
{"Secret":"","TestName":"TestFibonacci","Score":24,"MaxScore":28,"Weight":20}
```
In Go I use the first one to record the existence of this test, in case the test failed with a panic, and didn't output the score (the last line). However, even this isn't flawless. It still fails to record the later tests, if one of the first few fails with a panic. But maybe if you only have a single test, this would work for you as a gap-stop solution?

**Comment by meling** [comment]
BTW: I'm working on a new gRPC-based scoring framework, with the `Score` object defined in Protobuf. Hence, it can become easier to implement this also in a Python framework going forward. However, it is still early days, although I made a bit of progress yesterday; finally I was able to decide on some design issues, and make the API simple. The idea is to pre-register tests, their max score and weight over gRPC with QuickFeed, before starting to run student tests. This way we always know which tests should have been executed. If you want to take a look, it is in draft PR #384.
