### ISSUE TITLE
Log in issues

### ISSUE THREAD

**Issue by 0xf8f8ff** [autograde/quickfeed#513]
1. Authenticating with GitHub user can result in logging in as another user and being granted a full access this user has (be it admin or teacher)
2. Logging in with a browser that still keeps a user cookie set by another instance of Quickfeed will give an `Internal Server Error` even when a correct user and remote identity are saved in the current app's database. (`failed to associate user with remote identity   {"error": "remote identity registered with another user` error)

**Comment by meling** [comment]
Was this issue already resolved?

**Comment by JosteinLindhom** [comment]
I'm fairly sure this was resolved in #520.

The issue occured due to session cookies being an encrypted string that decodes to a struct containing the user ID.

If you have a database `["User A": 1, "User B": 2, "User C": 3]`, and `User B` log in - his session cookie contains ID = 2. Changing the database to `["User A": 1, "User C": 2, "User B": 3]` without invalidating the cookies will "trick" the server to thinking `User B` is now `User C`.

Generating a new secret key every time the server restarts resolves this.
https://github.com/autograde/quickfeed/blob/7f4bccea43e0f02002e132322e5109f2bad071a4/web/webserver.go#L39-L40
